package de.linushuck.utopia.skyblock.libs.api.enums.mob;

import de.linushuck.utopia.skyblock.libs.api.aaanewstructure.SkyBlockItemBuilder;
import de.linushuck.utopia.skyblock.libs.api.item.HeadCreator;
import lombok.Getter;


public enum BaseMobType
{
    PrivateIsland_Bat("Bat", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmRlNzVhMmNjMWM5NTBlODJmNjJhYmUyMGQ0Mjc1NDM3OWRmYWQ2ZjVmZjU0NmU1OGYxYzA5MDYxODYyYmI5MiJ9fX0="))),
    PrivateIsland_Creeper("Creeper", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM4NzBjODRiZjIxNTVjOTljYmE4ODk1ODhjYTkxZWY3OGU1OTBlNWVjNThiMmJmNzllODdhYTZkMTQ3M2RkMSJ9fX0="))),
    PrivateIsland_Enderman("Enderman", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTU5NjdlYjU4NmMyMzE4NzQzNDFiOTA0NGZkNzA4YzMzZTNmYzU5ODZkMjlmYTU5NzZiOGY3Yjk0ZmQxYzc3NSJ9fX0="))),
    PrivateIsland_Skeleton("Skeleton", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3ZWRkYzVmYTliNWIyOWM4ZjU4ODk4YmMxYjM5MzY3NmZkNWMxNzM4MDViZmQ1MmNiZWQwYzI5YmEzODY3NCJ9fX0="))),
    PrivateIsland_Slime("Slime", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQxYTMxOTdkNWQzYjU0YzNjYmI3ZDVmNzUzMDU5M2QxNDljN2ZlYzc1M2E1YWQ4ZjEwMjc2ZDI2NDM0MjcwNSJ9fX0="))),
    PrivateIsland_Spider("Spider", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzVlMjQ4ZGEyZTEwOGYwOTgxM2E2Yjg0OGEwZmNlZjExMTMwMDk3ODE4MGVkYTQxZDNkMWE3YThlNGRiYTNjMyJ9fX0="))),
    PrivateIsland_Witch("Witch", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0="))),
    PrivateIsland_Zombie("Zombie", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzgzYWFhZWUyMjg2OGNhZmRhYTFmNmY0YTBlNTZiMGZkYjY0Y2QwYWVhYWJkNmU4MzgxOGMzMTJlYmU2NjQzNyJ9fX0"))),

    Town_Crypt_Ghoul("Crypt Ghoul", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTY3MmI1YTNjZWNhNmNmOTYxOTZmNGZkOTkxMjllYmU4ZTM5MGJjN2YwYmJkYTcyYzg2MzRjMDk5OTgxZTFiZCJ9fX0="))),
    Town_Golden_Ghoul("Golden Ghoul", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTFkMWRjOTUwOWNlNGQzODI0YmU1ODNiNTlkMDM5YTgxMTMyNTAxZTc3YTg2ZmJlNTdmZGU0MGEzYTBhMDU4ZiJ9fX0="))),
    Town_Old_Wolf("Old Wolf", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRjNjQyOWNmYWJhY2YyMTFkZDNkYjI2YzVjYTdiNTk0MmRkODI1OTlmYmIxZDUzN2NmNzJlNDk1MmUyYzdiIn19fQ=="))),
    Town_Wolf("Wolf", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjlkMWQzMTEzZWM0M2FjMjk2MWRkNTlmMjgxNzVmYjQ3MTg4NzNjNmM0NDhkZmNhODcyMjMxN2Q2NyJ9fX0="))),
    Town_Graveyard_Zombie("Graveyard Zombie", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzgzYWFhZWUyMjg2OGNhZmRhYTFmNmY0YTBlNTZiMGZkYjY0Y2QwYWVhYWJkNmU4MzgxOGMzMTJlYmU2NjQzNyJ9fX0"))),
    Town_Zombie_Villager("Zombie Villager", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM3NTA1ZjIyNGQ1MTY0YTExN2Q4YzY5ZjAxNWY5OWVmZjQzNDQ3MWM4YTJkZjkwNzA5NmM0MjQyYzM1MjRlOCJ9fX0="))),

    FarmersYard_Chicken("Chicken", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2FkM2RkMDA4M2ZhYTY5YTA2MmY5YWQ4MTQxOGY1YTU5NjE4MGJmMTU5MmU0YjhkMTMwM2IyMzBiNjRiYzc5ZSJ9fX0="))),
    FarmersYard_Cow("Cow", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM0YjVmNmQ3NTEyNjM4MGY1MjBhNjdjYTU3YmM5YTU2YWExMWRiOGFmZTdlNWRjYjJhNTJkZmNmZWFlMDc4NSJ9fX0="))),
    FarmersYard_Pig("Pig", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWIxNzYwZTM3NzhmODA4NzA0NmI4NmJlYzZhMGE4M2E1Njc2MjVmMzBmMGQ2YmNlODY2ZDRiZWQ5NWRiYTZjMSJ9fX0="))),

    SandyCropland_Rabbit("Rabbit", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2QyNzE5MjcxYzcxNDk4MDIyNmZmMWJlZjRjYmIxZDU0NDExY2UzYTkxNGQ3ZGY3MzFiY2M3ZjYxZTk0ZTVjIn19fQ=="))),

    ShroomscapeDunes_Sheep("Sheep", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODRlNWNkYjBlZGIzNjJjYjQ1NDU4NmQxZmQwZWJlOTcxNDIzZjAxNWIwYjFiZmM5NWY4ZDVhZjhhZmU3ZTgxMCJ9fX0="))),
    ShroomscapeDunes_MushroomCow("Mooshroom Cow", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTU0M2I3MmRlZjFiMjQ3Njg1YWQ0ZDAyN2RmODZjOTYzMmU3ZGFjMTQzYTk1NTJlYzg5YzgwMDM1YzNiYTRhZSJ9fX0="))),

    WebbedCliff_Arachne("Arachne", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q1NDE1NDFkYWFmZjUwODk2Y2QyNThiZGJkZDRjZjgwYzNiYTgxNjczNTcyNjA3OGJmZTM5MzkyN2U1N2YxIn19fQ=="))),
    WebbedCliff_Arachne_Brood("Arachne Brood", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q1NDE1NDFkYWFmZjUwODk2Y2QyNThiZGJkZDRjZjgwYzNiYTgxNjczNTcyNjA3OGJmZTM5MzkyN2U1N2YxIn19fQ=="))),
    WebbedCliff_Arachne_Keeper("Arachne Keeper", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q1NDE1NDFkYWFmZjUwODk2Y2QyNThiZGJkZDRjZjgwYzNiYTgxNjczNTcyNjA3OGJmZTM5MzkyN2U1N2YxIn19fQ=="))),

    WebbedCliff_Broodmother("Broodmother", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWRmOWU2ODNhNTBjMzBlYjUxOTQyNjkyODIwNzkxMWNkNTZlMzEyYmI4ODFhNjA5OGFkYTA2MzllZTMzMzE2MCJ9fX0="))),

    WebbedCliff_Spider_Jockey("Spider Jockey", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA5MzkzNzNjYWZlNGIxZjUzOTdhYWZkMDlmM2JiMTY2M2U3YjYyOWE0MWE3NWZiZGMxODYwYjZiZjhiNDc1ZiJ9fX0="))),

    WebbedCliff_Gravel_Skeleton("Gravel Skeleton", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3ZWRkYzVmYTliNWIyOWM4ZjU4ODk4YmMxYjM5MzY3NmZkNWMxNzM4MDViZmQ1MmNiZWQwYzI5YmEzODY3NCJ9fX0="))),
    WebbedCliff_Rain_Slime("Rain Slime", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQxYTMxOTdkNWQzYjU0YzNjYmI3ZDVmNzUzMDU5M2QxNDljN2ZlYzc1M2E1YWQ4ZjEwMjc2ZDI2NDM0MjcwNSJ9fX0="))),
    WebbedCliff_Silverfish("Silverfish", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE5MWRhYjgzOTFhZjVmZGE1NGFjZDJjMGIxOGZiZDgxOWI4NjVlMWE4ZjFkNjIzODEzZmE3NjFlOTI0NTQwIn19fQ=="))),

    WebbedCliff_Dasher_Spider("Dasher Spider", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q1NDE1NDFkYWFmZjUwODk2Y2QyNThiZGJkZDRjZjgwYzNiYTgxNjczNTcyNjA3OGJmZTM5MzkyN2U1N2YxIn19fQ=="))),
    WebbedCliff_Splitter_Spider("Splitter Spider", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmFjZjY5ZmM3YWY1NDk3YTE3NDE4OTFkMWU1YmYzMmI5NmFlMGQ2YzBiYmQzYzE0NzU4ZWE0NGEwM2M1NzI4MyIsIm1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9fX19"))),
    WebbedCliff_Voracious_Spider("Voracious Spider", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjgxYjVjZjNhNjViZjljYWI0YmNhNTU3ODE3MjFhODZkNTY3ZDllMTA2NTUxNjQ3ZjM1YjcxNWVkZjAwYTEzZiJ9fX0="))),
    WebbedCliff_Weaver_Spider("Weaver Spider", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTIxNDM4ZjY0NmRjMDQ1MTU5NjdlODE5NWNjYzNkMzFlMjNiMDJmOWFhMGFjOTE0ZWRjMjgyMmY5ODM5NGI4NiIsIm1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9fX19"))),

    WebbedCliff_Jockey_Skeleton("Jockey Skeleton", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3ZWRkYzVmYTliNWIyOWM4ZjU4ODk4YmMxYjM5MzY3NmZkNWMxNzM4MDViZmQ1MmNiZWQwYzI5YmEzODY3NCJ9fX0="))),

    ShatteredEnd_Dragon("Dragon", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGY4MWM5ZDQyNjgwYWQ3YmM2ODZhMTI4MTA3M2ZiYmUyZmQ4MTYxOTEzZTVhM2JkOTk2OTNkMmM0MDRkODgyOCJ9fX0="))),
    ShatteredEnd_Enderman("Enderman", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTU5NjdlYjU4NmMyMzE4NzQzNDFiOTA0NGZkNzA4YzMzZTNmYzU5ODZkMjlmYTU5NzZiOGY3Yjk0ZmQxYzc3NSJ9fX0="))),
    ShatteredEnd_Endermite("Endermite", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWExYTA4MzFhYTAzYWZiNDIxMmFkY2JiMjRlNWRmYWE3ZjQ3NmExMTczZmNlMjU5ZWY3NWE4NTg1NSJ9fX0="))),
    ShatteredEnd_Nest_Endermite("Nest Endermite", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWE5NTM4NjlhMGM1M2U3YzVjMDEyMTE1YzJhNDMwM2NjYmZmOWQyZmI3OGJhZDRlMjhkMDY2ZWQxNmQwZjkxIn19fQ=="))),
    ShatteredEnd_Endstone_Protector("Endstone Protector", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTI4Y2ZkZWJhOWNhMGExOTcxOGNiNWU1ZmUxYTY5OGY0ZTQ3ODQxMTU1ZmMzOWUzZjc2MjI3NmZlZmM0MDM2ZSJ9fX0="))),
    ShatteredEnd_Obsidian_Defender("Obsidian Defender", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzRjMGU4MzMwNmU2OTU5OTJmMTFlYzI4YjIxNzQ5NjVkZTExNzdhMDM4NTAxZTI3YjJlYWY1MTU0N2Q5In19fQ=="))),
    ShatteredEnd_Watcher("Watcher", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmFiYmNkZDBhNWZlYjcyYWEyZTQzZGI5YWUyZmRkNDA2OTE5OGIxOWI1MTI2ZDliMTY0OTFjZTcxMjE2NmU3In19fQ=="))),
    ShatteredEnd_Zealot("Zealot", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjcxMDRiYTZmMDkzNWY3MTI5NjZkMDUxYmUwNGQ5OWZiODY3ZTg1N2JhZTRjZmYyZjJiMjQyOWVkMjM3M2M1ZSJ9fX0="))),
    ShatteredEnd_Special_Zealot("Special Zealot", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyMmNmMzNlYTZiZWI0NWQ2MjE3MDA2NWU3YzZjNGM1N2JmZmIwZTQ2MGEwNWE1YTE2M2IwN2RlNGZhYTIwMSJ9fX0="))),

    InfernoFortress_Blaze("Blaze", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjc4ZWYyZTRjZjJjNDFhMmQxNGJmZGU5Y2FmZjEwMjE5ZjViMWJmNWIzNWE0OWViNTFjNjQ2Nzg4MmNiNWYwIn19fQ=="))),
    InfernoFortress_MagmaCube("Magma Cube", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTFjOTdhMDZlZmRlMDRkMDAyODdiZjIwNDE2NDA0YWIyMTAzZTEwZjA4NjIzMDg3ZTFiMGMxMjY0YTFjMGYwYyJ9fX0="))),
    InfernoFortress_MagmaCube_Boss("Magma Cube Boss", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM3YjgzZjgxZTU4ZjJhMTE3OTg1YzY2Mjc3MTgzM2MzNGRhNjg0NDE3YzNhYTdlMjk2MGIwMTI3NWUzMWU5YSJ9fX0="))),
    InfernoFortress_Wither_Skeleton("Wither Skeleton", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTA2MWU1ZDVlZDY5YzViZDJlNzllNWJjNGNjYzk0NDEzZjE0M2UyYjVlODIxMzE3NjE1ZjI5YmYxYjIwMGI4NyJ9fX0="))),
    InfernoFortress_Ghast("Ghast", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjRhYjhhMjJlNzY4N2NjNGM3OGYzYjZmZjViMWViMDQ5MTdiNTFjZDNjZDdkYmNlMzYxNzExNjBiM2M3N2NlZCJ9fX0="))),
    InfernoFortress_Piglin("Piglin", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzljMjI4ZDc4ZTM5NTUwMGJjNTRlOGU0NWU5ODExYWY4YzllYTU4MDQ1ZDcyZmE2ZjA5OTIxZGE1N2UwNTViNCJ9fX0="))),

    RockyVeins_Sneaky_Creeper("Sneaky Creeper", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM4NzBjODRiZjIxNTVjOTljYmE4ODk1ODhjYTkxZWY3OGU1OTBlNWVjNThiMmJmNzllODdhYTZkMTQ3M2RkMSJ9fX0="))),
    RockyVeins_Lapis_Zombie("Lapis Zombie", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWMyMzJkMDY4M2JhMWUzNjI1OTNmYTFhOTdkNzQ0YzI5MGIxNjU1ZDcyYjIyNzc5ODhhNmM4NWE5Mzg1NDI1NSJ9fX0="))),
    RockyVeins_Redstone_Pigman("Redstone Pigman", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWVkODBiZjk5ZGZiMDc1MTkyYjAyYTVkZDZiZjkxZWRkZDRjYjFmNDgxODkyMzIxMjExZmUyMTQyZDlkZjIyYyJ9fX0="))),
    RockyVeins_Emerald_Slime("Emerald Slime", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQxYTMxOTdkNWQzYjU0YzNjYmI3ZDVmNzUzMDU5M2QxNDljN2ZlYzc1M2E1YWQ4ZjEwMjc2ZDI2NDM0MjcwNSJ9fX0="))),
    RockyVeins_Miner_Skeleton("Miner Skeleton", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3ZWRkYzVmYTliNWIyOWM4ZjU4ODk4YmMxYjM5MzY3NmZkNWMxNzM4MDViZmQ1MmNiZWQwYzI5YmEzODY3NCJ9fX0="))),
    RockyVeins_Miner_Zombie("Miner Zombie", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzgzYWFhZWUyMjg2OGNhZmRhYTFmNmY0YTBlNTZiMGZkYjY0Y2QwYWVhYWJkNmU4MzgxOGMzMTJlYmU2NjQzNyJ9fX0="))),

    WoodlandPark_Howling_Spirit("Howling Spirit", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA2NmNlZmRhODAzNTQzYjczNmU5NmEzMjY2M2EwODc1NTdmMTI4OWVhMWVkNjBhNTE3NTQxM2NhNjBjODRiYSJ9fX0="))),
    WoodlandPark_Pack_Spirit("Pack Spirit", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODgyMmFiOWFlNDkzODUwOTdhYTU3MmU5NzQxNDRkYzU5ZDZiZGNlM2ZiZmUxMDUyMjQwZjk4NTgzMjg1YTczNyJ9fX0="))),
    WoodlandPark_Soul_of_the_Alpha("Soul of the Alpha", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZhM2M3NTIxM2JlNGFjNmUxMjA5YjEyZmI2MGZjY2E5YWY3ODJhY2I3MmZiZTgyZmUzNTc3MzNlM2M3OTcxMSJ9fX0="))),

    DwarvensDelve_Goblin("Goblin", new SkyBlockItemBuilder(HeadCreator.createCustomHead("ewogICJ0aW1lc3RhbXAiIDogMTYxNTE2MTQ5NzA2MCwKICAicHJvZmlsZUlkIiA6ICJjZGM5MzQ0NDAzODM0ZDdkYmRmOWUyMmVjZmM5MzBiZiIsCiAgInByb2ZpbGVOYW1lIiA6ICJSYXdMb2JzdGVycyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82NTJjZTE0Y2IwZDZhNTJiNWNiMTA2Y2JhYTU4ZTFkMTI5MGRjY2YzNDFhNWZiNzQ4ZGE2MTIyZGQ5NTcxNWY5IgogICAgfQogIH0KfQ"))),
    DwarvensDelve_Star_Sentry("Star Sentry", new SkyBlockItemBuilder(HeadCreator.createCustomHead("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDg3YjhmM2NmMWMxMDE0ODgzMjc2ZjIzMDUwMWQ1YWYxMzk3Njk5MDcxYmZhYjFlZTI5NGM4NjE3MjJjYzJmIn19fQ=="))),

    ;

    @Getter
    private final String name;

    @Getter
    private final SkyBlockItemBuilder itemBuilder;

    BaseMobType(String name, SkyBlockItemBuilder itemBuilder)
    {
        this.name = name;
        this.itemBuilder = itemBuilder;
    }
}
